/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package views;

import Controllers.ProductController;
import Controllers.OrderController;
import Controllers.StockController;
import Exceptions.ModelNotCreatedExeception;
import Models.Order;
import Models.Product;
import Models.Stock;
import Enums.Type;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author patri
 */
public class Pedidos extends javax.swing.JDialog {

    /**
     * Creates new form Pedidos
     */
    public Pedidos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        fillProductComboBox(jComboBox_TipoSalgado, Enums.Type.FOOD);
        fillProductComboBox(jComboBox_TipoSuco, Enums.Type.DRINK);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel_TituloTelaPedido = new javax.swing.JLabel();
        jLabel_NPedido = new javax.swing.JLabel();
        jLabel_TipoSalgado = new javax.swing.JLabel();
        jLabel_TipoSuco = new javax.swing.JLabel();
        jComboBox_TipoSalgado = new javax.swing.JComboBox<>();
        jComboBox_TipoSuco = new javax.swing.JComboBox<>();
        jTextField_NPedido = new javax.swing.JTextField();
        jCheckBox_EhPromocao = new javax.swing.JCheckBox();
        jButton_Anotar = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton_Editar = new javax.swing.JButton();
        jButton_Editar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel_TituloTelaPedido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel_TituloTelaPedido.setText("PEDIDOS");

        jLabel_NPedido.setText("Nº Pedido:");

        jLabel_TipoSalgado.setText("Tipo Salgado:");

        jLabel_TipoSuco.setText("Tipo Suco:");

//        jComboBox_TipoSalgado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox_TipoSalgado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoSalgadoActionPerformed(evt);
            }
        });

//        jComboBox_TipoSuco.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-" }));
        jComboBox_TipoSuco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_TipoSucoActionPerformed(evt);
            }
        });

        jCheckBox_EhPromocao.setText("É promoção ?");

        jButton_Anotar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Anotar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Anotar.setText("REGISTRAR");
        jButton_Anotar.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnotarActionPerformed(evt);
            }
        });

        jButton_Listar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Listar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Listar.setText("LISTAR");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nº Pedido", "Salgado", "Bebida", "Promoção", "Total (R$)"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton_Editar.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Editar.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Editar.setText("EDITAR");
        jButton_Editar.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditarActionPerformed(evt);
            }
        });

        jButton_Editar1.setBackground(new java.awt.Color(0, 0, 0));
        jButton_Editar1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_Editar1.setText("EXCLUIR");
        jButton_Editar1.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Editar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(jLabel_TituloTelaPedido)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel_TipoSalgado)
                            .addComponent(jLabel_NPedido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jComboBox_TipoSalgado, 0, 147, Short.MAX_VALUE)
                            .addComponent(jTextField_NPedido)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel_TipoSuco)
                        .addGap(22, 22, 22)
                        .addComponent(jComboBox_TipoSuco, 0, 147, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 188, Short.MAX_VALUE)
                        .addComponent(jCheckBox_EhPromocao, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton_Anotar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Listar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_Editar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Editar1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_TituloTelaPedido)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_NPedido)
                            .addComponent(jTextField_NPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_TipoSalgado)
                            .addComponent(jComboBox_TipoSalgado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_TipoSuco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_TipoSuco)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jCheckBox_EhPromocao)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_Anotar)
                            .addComponent(jButton_Listar)
                            .addComponent(jButton_Editar)
                            .addComponent(jButton_Editar1))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jButton_AnotarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (jTextField_NPedido.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha o numero do pedido antes de registrar.");
                return;
            }
            int pedido = Integer.parseInt(jTextField_NPedido.getText());
            Product salgado = (Product)jComboBox_TipoSalgado.getSelectedItem();
            Product bebida = (Product)jComboBox_TipoSuco.getSelectedItem();
            boolean promocao = jCheckBox_EhPromocao.isSelected();
            ProductController productController = new ProductController();
            OrderController orderController = new OrderController();
            String str_salgado = jComboBox_TipoSalgado.getSelectedItem().toString();
            String str_bebida = jComboBox_TipoSuco.getSelectedItem().toString();
            Double valorComida = productController.ValorProduto(str_salgado, 1);
            Double valorBebida = productController.ValorProduto(str_bebida,1);
            float valorComidaFloat = valorComida.floatValue();
            float valorBebidaFloat = valorBebida.floatValue();
            float preco = orderController.calcularTotalDosItens(valorComidaFloat, valorBebidaFloat, promocao);

            ArrayList<Product> lista_produto = new ArrayList<Product>();

            Product produtoSalgado = productController.getByProduct(salgado);
            Product produtoBebida = productController.getByProduct(bebida);


            if (produtoSalgado != null) {
                lista_produto.add(produtoSalgado);
            } else {
                JOptionPane.showMessageDialog(this, "Salgado não cadastrado.");
                return;
            }

            if (produtoBebida != null) {
                lista_produto.add(produtoBebida);
            } else {
                JOptionPane.showMessageDialog(this, "Bebida não cadastrada.");
                return;
            }
            System.out.println(lista_produto);
            orderController.add(new Order(pedido, lista_produto, promocao, preco));
            jTextField_NPedido.setText("");
            JOptionPane.showMessageDialog(this, "Produto registrado com sucesso.");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao registrar o produto." + ex.getMessage());
        }
    }
    private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt){
        OrderController orderController = new OrderController();

        ArrayList<Order> orders = orderController.get();

        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Nº Pedido");
        modelo.addColumn("Salgado");
        modelo.addColumn("Bebida");
        modelo.addColumn("Promoção");
        modelo.addColumn("Total (R$)");


        for (Order order : orders) {
            if (order.products.size() == 2) {
                Product salgado = order.products.get(0);
                Product bebida = order.products.get(1);
                modelo.addRow(new Object[]{order.id, salgado, bebida, order.isPromotion, order.total});
            }
        }

        jTable2.setModel(modelo);
        jTable2.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int rowIndex = jTable2.getSelectedRow();
                if(rowIndex != -1) {
                    OrderController orderController = new OrderController();
                    ArrayList<Order> orders = orderController.get();
                    Order order = orders.get(rowIndex);

                    jTextField_NPedido.setText(String.valueOf(order.id));
                    jComboBox_TipoSalgado.setSelectedItem(order.products);
                    jComboBox_TipoSuco.setSelectedItem(order.products);
                    jCheckBox_EhPromocao.setSelected(order.isPromotion);


                }
            }

        });

    }

    private void jButton_Editar1ActionPerformed(java.awt.event.ActionEvent evt) {
        int numeroPedidoParaDeletar = Integer.parseInt(jTextField_NPedido.getText());
        OrderController orderController = new OrderController();
        try {
            orderController.deleteByNumeroPedido(numeroPedidoParaDeletar);
            JOptionPane.showMessageDialog(this, "Pedido deletado com sucesso.");
        } catch (ModelNotCreatedExeception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar o pedido: " + ex.getMessage());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro ao deletar o pedido: " + ex.getMessage());
        }
    }//GEN-LAST:event_jButton_EditarActionPerformed

    private void jButton_EditarActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            int numeroPedidoParaDeletar = Integer.parseInt(jTextField_NPedido.getText());
            OrderController ordecontroller = new OrderController();
            Order order = ordecontroller.getById(numeroPedidoParaDeletar);
            ordecontroller.update(order);
        } catch (Exception ex) {
            Logger.getLogger(Estoque.class.getName()).log(Level.SEVERE, null, ex);
        }
    }



    private void jComboBox_TipoSalgadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoSalgadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TipoSalgadoActionPerformed

    private void jComboBox_TipoSucoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_TipoSucoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_TipoSucoActionPerformed

    private void fillProductComboBox(JComboBox<Product> comboBox, Enums.Type type) {
        ProductController productController = new ProductController();
        ArrayList<Product> products = productController.get();

        comboBox.removeAllItems();

        for (Product product : products) {
            if (product.type == type) {
                comboBox.addItem(product);
            }
        }
    }

    /**
     * Creates new form Pedidos
     */



    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Pedidos dialog = new Pedidos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anotar;
    private javax.swing.JButton jButton_Editar;
    private javax.swing.JButton jButton_Editar1;
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JCheckBox jCheckBox_EhPromocao;
    private javax.swing.JComboBox<Product> jComboBox_TipoSalgado;
    private javax.swing.JComboBox<Product> jComboBox_TipoSuco;
    private javax.swing.JLabel jLabel_NPedido;
    private javax.swing.JLabel jLabel_TipoSalgado;
    private javax.swing.JLabel jLabel_TipoSuco;
    private javax.swing.JLabel jLabel_TituloTelaPedido;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField_NPedido;
    // End of variables declaration//GEN-END:variables
}
